---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Ensure base packages are installed"
  package:
    name: "{{ basetools_packages }}"
    state: present
  register: basetools_install_basetools
  until: basetools_install_basetools is succeeded
  retries: 3
